// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etidgalrxeujyuatrfvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0aWRnYWxyeGV1anl1YXRyZnZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzMDgzMjksImV4cCI6MjA1Mzg4NDMyOX0.rq9jhgPQONCpT1OptukJCWWsnPkd4pQl_8j0DsbcmoI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);